preload = /home/glebbox/dotfiles/.config/hypr/wallpaper/AgnesTachyonWallPP.jpg

wallpaper {
    monitor =
    path = /home/glebbox/dotfiles/.config/hypr/wallpaper/AgnesTachyonWallPP.jpg
}

splash = false
