-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--Самое важное
require("configs.variables")
require("configs.programs")
--Железо и визуал
require("configs.monitors")
require("configs.style")
require("configs.input")
require("configs.etc")
--Воркспейсы
require("configs.workspace")
--Все остальное
require("configs.keybinds")
require("configs.autostart")
